redis:
  host: 127.0.0.1
  port: 6379

time_load_message: 10

twitter:
  consumer_key: KF9XhulcbJijkJiMHYHEBg
  consumer_secret: sjN3i4vBMDIe00STFhEGEdJm3osByNfw8imcHkAxU
  access_token: 390302140-8RmzV2coFt35dJUhpccglJepFWCmLgUbddWZBb7f
  access_token_secret: 2fZ2vSBS0Gv9rcdo1AuxfDK47S7h3ac7UCD0EcZ2gdDiQ
  url: http://api.twitter.com/
